config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :flats
  # Defines the root path route ("/")
  # root "posts#index"

  root "flats#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  def index
    @flats = Flat.all
  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def edit
  end

  def create
    @flat = Flat.new(flat_params)

    if @flat.save
      redirect_to @flat, notice: "Flat was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @flat.update(flat_params)
      redirect_to @flat, notice: "Flat was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @flat.destroy!
    redirect_to flats_url, notice: "Flat was successfully destroyed.", status: :see_other
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_flat.html.erb
<div id="<%= dom_id flat %>" class="card glass w-96">
  <figure>
    <img
      src="https://a0.muscache.com/im/pictures/46315410-e42d-4891-be78-66d6bd97e72f.jpg?im_w=720&im_format=avif"
      alt="car!" />
  </figure>
  <div class="card-body">
    <h2 class="card-title">
          <strong></strong>
    <%= flat.name %>
    </h2>
    <p>
          <strong></strong>
    <%= flat.address %>
    </p>
       <p>
          <strong></strong>
    <%= flat.description %>
    </p>
       <p>
          <strong> <%= flat.number_of_guests %> </strong> <i class="fa-solid fa-users"></i>
    </p>
    <div class="card-actions justify-end items-center">

       <p class="size_cost">
        <strong> <%= flat.price_per_night %> </strong> <i class="fa-solid fa-dollar-sign"></i>/night
    </p>
    <% if button %>
      <button class="btn btn-outline"><%= link_to "Book this flat", flat %></button>
          <% end %>
    </div>
  </div>
</div>

app/views/flats/_form.html.erb
<%= simple_form_for(@flat) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
 <div class="form-inputs button_border">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
  </div>
<div class="form-actions button_border">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/flats/_list.html.erb
<% flats.each do |flat| %>
  <%= render flat, button:true %>
<% end %>

app/views/flats/edit.html.erb
<h1 class="text-center title">EDIT FLAT</h1>
<div class="flex items-center justify-center h-screen text-center width-div">
<%= render "form", flat: @flat %>
</div>

<br>
<div class="text-center">
  <%= link_to "Show this flat", @flat %> |
  <%= link_to "Back to flats", flats_path %>
</div>

app/views/flats/index.html.erb
<p style="color: green"><%= notice %></p>

<div id="flats" class="background-cards flex items-stretch gap-3">
  <%= render "list", flats: @flats %>
</div>

app/views/flats/new.html.erb
<h1 class="text-center title">NEW FLAT</h1>

<div class="flex items-center justify-center h-screen text-center width-div">
<%= render "form", flat: @flat %>
</div>

<br>

<div class="text-center">
  <%= link_to "Back to flats", flats_path %>
</div>

app/views/flats/show.html.erb
<div class="flex justify-items-center gap-3 p-3">
<div>
<p style="color: green"><%= notice %></p>
<%= render @flat, button:false %>
</div>

<div class="mockup-code max-w-sm">
  <pre data-prefix="$"><code> <%= link_to "Edit this flat", edit_flat_path(@flat) %> </code></pre>
  <pre data-prefix=">" class="text-warning"><code> <%= link_to "Back to flats", flats_path %> </code></pre>
  <pre data-prefix=">" class="text-success"><code> <%= link_to "Destroy this flat", @flat, method: :delete %> </code></pre>
</div>

<div class="mockup-window bg-base-300 border widthomg">
  <div class="border-base-300 flex justify-center border-t px-4 py-16"><img src="https://i.ibb.co/pjjMc68f/Screenshot-2025-02-26-at-15-25-05.png" alt="" class="img_width"></div>
</div>

<div class="stats stats-vertical shadow">
  <div class="stat">
    <div class="stat-title">Discount (value/day)</div>
    <div class="stat-value"> 1̶0̶0̶ <strong>75$</strong></div>
    <div class="stat-desc">2 days left</div>
  </div>

  <div class="stat">
    <div class="stat-title">Duration</div>
    <div class="stat-value">6 nights</div>
    <div class="stat-desc"> 20/02 to 27/02</div>
  </div>

  <div class="stat">
    <div class="stat-title">Animals</div>
    <div class="stat-value"><i class="fa-solid fa-dog"></i></div>
    <div class="stat-desc">Dogs are allowed!</div>
  </div>
</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-theme="forest">
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

<link href="https://cdn.jsdelivr.net/npm/daisyui@4.12.24/dist/full.min.css" rel="stylesheet" type="text/css" />
<script src="https://cdn.tailwindcss.com"></script>
<%# <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"> %>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="h-200">
    <div class="navbar background_navbar">
  <div class="flex-1">
    <a class="btn btn-ghost text-xl" href="/flats">WaterBNB</a>
  </div>
  <div class="flex-none">
    <ul class="menu menu-horizontal px-1">
      <li><a href="/flats/new">Add a flat</a></li>
    </ul>
  </div>
</div>
    <%= yield %>
  </body>
</html>